# Site settings
title: Quercus Coaching
header-img: img/banner_photo.png
email: akmacduff@gmail.com
description: "Create a life that you love."
# url: "https://akmacduffgithubio-akmacduff.c9users.io/"
url: ""
baseurl: ""
github_username:  akmacduff

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]